"""update_products

Revision ID: 5ebe4cec858d
Revises: 0af4eaaf73eb
Create Date: 2024-12-20 12:22:11.373986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebe4cec858d'
down_revision: Union[str, None] = '0af4eaaf73eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_unique_constraint('_user_product_rating_uc', 'ratings', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_product_rating_uc', 'ratings', type_='unique')
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
