"""update_user/access to refresh token

Revision ID: c00e09bf5b2b
Revises: 6136a54bc254
Create Date: 2024-12-21 16:31:16.578992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00e09bf5b2b'
down_revision: Union[str, None] = '6136a54bc254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=False))
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
